### ISSUE TITLE
Feature Request - Constraining Covariates

### ISSUE THREAD

**Issue by mwh3780** [nanxstats/msaenet#1]
It would be useful if the functions in this package supported or provided arguments similar to `glmnet::glmnet()`'s `lower.limits` and `upper.limits`. I frequently run adaptive elastic nets using `glmnet` and regularly have to constrain covariates to be non-negative or non-positive.

**Comment by nanxstats** [comment]
@michaelwhammer -- that's a very good suggestion -- as I'm going to make more important vanilla glmnet/ncvreg arguments available for msaenet, this one could have a high priority.

**Comment by mwh3780** [comment]
Additionally, if it's possible to enable a `...` argument to allow for any argument to passed on to  glmnet/ncvreg. I don't know if this would cause confusion as many arguments in `msaenet` seem to be wrappers around arguments in glmnet/ncvreg.

**Comment by nanxstats** [comment]
-- that is a very good point. I guess there is a certain balance between the flexibility and clarity for the API design:

- `...` was supported in the first versions, then it was removed on purpose to avoid possible confusions. If you look into the code, the internal parameter tuning functions support `...`, while the current implementation does not expose this API to the user. This ensures clarity but sacrifices flexibility.
- another design consideration would be keeping the high-level interface of different wrappers for glmnet and ncvreg as similar/consistent as possible -- so only a minimal but critical set of arguments was selected in the present implementation. This also increases clarity while decreases flexibility.

After these, we can consider adding more flexibility -- `lower.limits`/`upper.limits` can be a good start.

**Comment by nanxstats** [comment]
@michaelwhammer  -- this has been fixed by https://github.com/road2stat/msaenet/commit/5e10777c3e4ff4b284d9eb1b21847702bfd4fd4c. The new version (v2.6) has been submitted to CRAN. In the same time, you can try the GitHub version using

```r
devtools::install_github("road2stat/msaenet")
```

Here is some code for testing:

```r
library("msaenet")

dat = msaenet.sim.gaussian(
  n = 150, p = 500, rho = 0.6,
  coef = rep(2, 5), snr = 5, p.train = 0.7,
  seed = 1001)

fit0 = msaenet(
  dat$x.tr, dat$y.tr,
  alphas = seq(0.05, 0.95, 0.05),
  nsteps = 3L, seed = 1003)

print(fit0)
msaenet.nzv(fit0)
msaenet.fp(fit0, 1:5)
msaenet.tp(fit0, 1:5)
msaenet.pred = predict(fit0, dat$x.te)
msaenet.rmse(dat$y.te, msaenet.pred)
plot(fit0)

fit1 = msaenet(
  dat$x.tr, dat$y.tr,
  alphas = seq(0.05, 0.95, 0.05),
  nsteps = 3L, lower.limits = 0L,
  seed = 1003)

print(fit1)
msaenet.nzv(fit1)
msaenet.fp(fit1, 1:5)
msaenet.tp(fit1, 1:5)
msaenet.pred = predict(fit1, dat$x.te)
msaenet.rmse(dat$y.te, msaenet.pred)
plot(fit1)
```

Please feel free to let me know if it does not work as expected. Thanks!

-Nan
