### ISSUE TITLE
Can I compute p value using the library msaenet?

### ISSUE THREAD

**Issue by runnytone** [nanxstats/msaenet#5]
Can I compute p-value using the library msaenet?

**Comment by nanxstats** [comment]
Not currently. There is usually no such thing (p-values) for regularized linear models, while there are surely some post-selection inference methods out there, for example: https://projecteuclid.org/euclid.ss/1449670857.

It shouldn't be too difficult to implement these, but I don't really have plans right now.

**Comment by runnytone** [comment]
Thank you.
